# PowerShell helper: generate mapping of existing commits to random dates in 2023
# Usage: run from the repository root in PowerShell:
#   .\tools\generate-2023-git-dates.ps1
# It will write tools/commit-date-mapping.csv and tools/env-filter.sh.
# After reviewing the generated env-filter.sh, run the rewrite in Git Bash or WSL:
#   git backup: create a branch to preserve original history:
#     git branch before-randomize
#   In Git Bash / WSL: git filter-branch --env-filter 'source ./tools/env-filter.sh' -- --all
# Then force-push to remote if desired (beware: rewriting history requires force push and affects collaborators).

param()

function Ensure-GitRepo {
    $isRepo = & git rev-parse --is-inside-work-tree 2>$null
    if ($LASTEXITCODE -ne 0) { throw "Not inside a git repository." }
}

function Get-CommitList {
    # reverse chronological -> chronological: older commits first
    $commits = & git rev-list --all --reverse
    if ($LASTEXITCODE -ne 0) { throw "Failed to list commits." }
    return $commits -split "\n" | Where-Object { $_ -ne '' }
}

function Random-Date-2023 {
    param($weekdayBias = 5, $weekendBias = 1)
    # Select a random day in 2023 with weekday bias > weekend bias
    while ($true) {
        $start = [datetime]::ParseExact("2023-01-01","yyyy-MM-dd",$null)
        $end = [datetime]::ParseExact("2023-12-31","yyyy-MM-dd",$null)
        $range = ($end - $start).Days + 1
        $offset = Get-Random -Minimum 0 -Maximum $range
        $candidate = $start.AddDays($offset)
        $dayOfWeek = $candidate.DayOfWeek
        $weight = if ($dayOfWeek -eq 'Saturday' -or $dayOfWeek -eq 'Sunday') { $weekendBias } else { $weekdayBias }
        # Accept with probability proportional to weight/weekdayBias (so larger bias -> more likely)
        $roll = Get-Random -Minimum 1 -Maximum ($weekdayBias + $weekendBias)
        if ($roll -le $weight) { 
            # pick random time between 06:00 and 22:00 local
            $hour = Get-Random -Minimum 6 -Maximum 22
            $minute = Get-Random -Minimum 0 -Maximum 60
            $second = Get-Random -Minimum 0 -Maximum 60
            $dt = Get-Date -Year $candidate.Year -Month $candidate.Month -Day $candidate.Day -Hour $hour -Minute $minute -Second $second -Millisecond 0
            # Format as RFC2822 style which git accepts: 'Tue, 18 Jul 2023 14:23:05 +0000'
            # For reproducibility use UTC timezone
            $dtUtc = $dt.ToUniversalTime()
            return $dtUtc.ToString("ddd, dd MMM yyyy HH:mm:ss +0000")
        }
    }
}

try {
    Ensure-GitRepo
    Write-Host "Repository detected. Collecting commits..."
    $commits = Get-CommitList
    Write-Host "Found $($commits.Count) commits. Generating randomized 2023 dates (fewer on weekends)..."

    $outCsv = "tools\\commit-date-mapping.csv"
    $envSh = "tools\\env-filter.sh"

    $lines = @()
    $caseLines = @()
    foreach ($c in $commits) {
        $date = Random-Date-2023 -weekdayBias 5 -weekendBias 1
        $lines += "$c,$date"
        $caseLines += "    $c) export GIT_AUTHOR_DATE=\"$date\"; export GIT_COMMITTER_DATE=\"$date\";;"
    }

    # Write CSV mapping
    Set-Content -Path $outCsv -Value ("commit,date" + "`n" + ($lines -join "`n")) -Encoding UTF8
    Write-Host "Wrote $outCsv"

    # Write env-filter.sh with a case statement (sourced by git filter-branch)
    $script = @()
    $script += "#!/bin/sh"
    $script += "# Generated by tools/generate-2023-git-dates.ps1 — review before use"
    $script += "case \"\$GIT_COMMIT\" in"
    $script += $caseLines
    $script += "    *) ;;"
    $script += "esac"

    Set-Content -Path $envSh -Value ($script -join "`n") -Encoding UTF8
    Write-Host "Wrote $envSh"

    Write-Host "Done. Next steps (VERY IMPORTANT):" -ForegroundColor Yellow
    Write-Host "  1) Inspect $outCsv and $envSh to verify the mapping and dates." -ForegroundColor Yellow
    Write-Host "  2) Create a backup branch: git branch before-randomize" -ForegroundColor Yellow
    Write-Host "  3) Run the rewrite in Git Bash or WSL (not PowerShell):" -ForegroundColor Yellow
    Write-Host "       git filter-branch --env-filter 'source ./tools/env-filter.sh' -- --all" -ForegroundColor Yellow
    Write-Host "  4) Verify history locally, then force-push to remote if you want to replace remote history:" -ForegroundColor Yellow
    Write-Host "       git push --force origin --all" -ForegroundColor Yellow
    Write-Host "WARNING: Rewriting history changes commit SHAs. If you push, collaborators must re-clone or rebase."
} catch {
    Write-Error $_.Exception.Message
}
